memberaudit/urls.py
from django.urls import path

from .views import (
    admin,
    character_finder,
    character_viewer_1,
    character_viewer_2,
    characters,
    data_export,
    reports,
)

app_name = "memberaudit"

urlpatterns = [
    # characters
    path("", characters.index, name="index"),
    path("launcher", characters.launcher, name="launcher"),
    path("add_character", characters.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        characters.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        characters.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        characters.unshare_character,
        name="unshare_character",
    ),
    # character viewer
    path(
        "character_viewer/<int:character_pk>/",
        character_viewer_1.character_viewer,
        name="character_viewer",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        character_viewer_1.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        character_viewer_1.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        character_viewer_1.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        character_viewer_1.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        character_viewer_1.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        character_viewer_1.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        character_viewer_2.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        character_viewer_2.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        character_viewer_2.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail/<int:character_pk>/<int:mail_pk>/",
        character_viewer_2.character_mail,
        name="character_mail",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        character_viewer_2.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        character_viewer_2.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        character_viewer_2.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        character_viewer_2.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        character_viewer_2.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        character_viewer_2.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        character_viewer_1.character_attribute_data,
        name="character_attribute_data",
    ),
    # character finder
    path(
        "character_finder", character_finder.character_finder, name="character_finder"
    ),
    path(
        "character_finder_data",
        character_finder.CharacterFinderListJson.as_view(),
        name="character_finder_data",
    ),
    path(
        "character_finder_list_fdd_data",
        character_finder.character_finder_list_fdd_data,
        name="character_finder_list_fdd_data",
    ),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "user_compliance_report_data",
        reports.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        reports.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        reports.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    # data export
    path("data-export/", data_export.data_export, name="data_export"),
    path(
        "data-export/run-update/<str:topic>",
        data_export.data_export_run_update,
        name="data_export_run_update",
    ),
    path(
        "data-export/download/<str:topic>",
        data_export.download_export_file,
        name="download_export_file",
    ),
    # admin
    path(
        "admin/create-skillset-from-fitting",
        admin.admin_create_skillset_from_fitting,
        name="admin_create_skillset_from_fitting",
    ),
]

memberaudit/templates/memberaudit/partials/character_viewer/overview.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

<!-- Character summary panel -->
<div class="panel panel-default">
    <div class="panel-heading">{% translate 'Overview' %}</div>
    <div class="panel-body">
        <div class="character-summary-flex">
            <div class="character-summary-image hidden-xs">
                <p class="text-center">
                    <img width="128" height="128" class="img-rounded"
                        src="{{ auth_character|character_portrait_url:128 }}" />
                </p>

                <p class="text-center">
                    <a href="{{ auth_character|zkillboard_character_url }}" target="_blank">
                        <img src="{% static 'memberaudit/images/zkillboard.png' %}"
                            title="{{ auth_character.character_name }} on zKillboard">
                    </a>

                    <a href="{{ auth_character|evewho_character_url }}" target="_blank">
                        <img src="{{ 1|character_portrait_url:32 }}"
                            title="{{ auth_character.character_name }} on EveWho" width="16px" height="16px">
                    </a>

                    <a href="https://forums.eveonline.com/u/{{ auth_character.character_name.split|join:'_' }}/summary"
                        target="_blank">
                        <img src="{% static 'memberaudit/images/evelogo.png' %}"
                            title="{{ auth_character.character_name }} on Eve Forums" width="16px" height="16px">
                    </a>

                    <a href="https://eve-search.com/search/author/{{ auth_character.character_name }}" target="_blank">
                        <img src="{% static 'memberaudit/images/evesearch.png' %}"
                            title="{{ auth_character.character_name }} on Eve Search" width="16px" height="16px">
                    </a>

                    <a href="https://eve-prism.com/?view=character&name={{ auth_character.character_name }}"
                        target="_blank">
                        <img src="{% static 'memberaudit/images/eve-prism.png' %}"
                            title="{{ auth_character.character_name }} on Eve Prism" width="16px" height="16px">
                    </a>
                </p>
            </div>

            {% translate "(no data yet)" as no_data %}

            <div class="character-summary-info">
                <div class="row">
                    <div class="col-md-6 col-lg-4">
                        <dl class="dl-horizontal">
                            <dt>{% translate 'Character:' %}</dt>
                            <dd class="nowrap">
                                {{ auth_character.character_name }}
                                {% if auth_character.character_id == main_character_id %}
                                &nbsp;<i class="fas fa-crown" title="Main character"></i>
                                {% endif %}

                                {% if character.is_shared %}
                                &nbsp;<i class="far fa-eye" title="Currently shared with recruiters"></i>
                                {% endif %}
                            </dd>

                            <dt>{% translate 'Corporation:' %}</dt>
                            <dd>
                                <a href="{{ auth_character.corporation_name|dotlan_corporation_url }}" target="_blank">
                                    {{ auth_character.corporation_name }}
                                </a>
                            </dd>

                            <dt>{% translate 'Alliance:' %}</dt>
                            <dd>
                                {% if auth_character.alliance_name %}
                                <a href="{{ auth_character.alliance_name|dotlan_alliance_url }}" target="_blank">
                                    {{ auth_character.alliance_name }}
                                </a>
                                {% else %}
                                -
                                {% endif %}
                            </dd>

                            <dt>{% translate 'Faction:' %}</dt>
                            {% if character_details %}
                                <dd>{{ character_details.faction|default:"-" }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Race:' %}</dt>
                            {% if character_details %}
                                <dd>{{ character_details.eve_bloodline.eve_race }} / {{ character_details.eve_bloodline }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}
                        </dl>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <dl class="dl-horizontal">
                            <dt>{% translate 'Born:' %}</dt>
                            {% if character_details %}
                                <dd>{{ character_details.birthday|naturaltime }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Skillpoints:' %}</dt>
                            {% if character.skillpoints %}
                                <dd>{{ character.skillpoints.total|intword }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Sec. Status:' %}</dt>
                            {% if character_details.security_status %}
                                <dd
                                    class="{% if character_details.security_status < 0 %}text-danger{% elif character_details.security_status > 0 %}text-success{% endif %}">
                                    {{ character_details.security_status|floatformat:1 }}
                                </dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Assets:' %}</dt>
                            {% if character_assets_total %}
                                <dd>{{ character_assets_total|intword }} ISK (est.)</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Wallet:' %}</dt>
                            {% if character.wallet_balance %}
                                <dd>{{ character.wallet_balance.total|intword }} ISK</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}
                        </dl>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <dl class="dl-horizontal">
                            <dt>{% translate 'Location:' %}</dt>
                            {% if character.location %}
                                <dd>{{ character.location.location.name_plus }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Ship:' %}</dt>
                            {% if character.ship %}
                                <dd>{{ character.ship.eve_type.name }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'System:' %}</dt>
                            <dd>{% include 'memberaudit/partials/solar_system.html' with character=character only %}</dd>

                            <dt>{% translate 'Last Login:' %}</dt>
                            {% if character.online_status.last_login %}
                                <dd class="nowrap">{{ character.online_status.last_login|naturaltime }}</dd>
                            {% else %}
                                <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Main:' %}</dt>
                            <dd>{{ main|default:"-" }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

memberaudit/templates/memberaudit/partials/character_viewer/sidebar.html
{% load i18n %}
{% load static %}
{% load evelinks %}

<!-- Sidebar panel-->
<div class="panel panel-default">
    <div class="panel-heading">Characters</div>
    <div class="panel-body">
        <ul class="sidebar_characters">
            {% for character in all_characters %}
                {% if character.memberaudit_character_pk and character.has_access%}
                    <li class="sidebar_character character-{{ character.memberaudit_character_pk }}{% if auth_character.character_name == character.character_name %} active{% endif %}">
                        <a href="{% url 'memberaudit:character_viewer' character.memberaudit_character_pk %}">
                            {% include "memberaudit/partials/character_viewer/sidebar_character.html" %}
                        </a>
                    </li>
                {% else %}
                    <li class="sidebar_character_disabled">
                        {% include "memberaudit/partials/character_viewer/sidebar_character.html" %}&nbsp;
                        <i class="fas fa-exclamation-triangle text-muted" title="Unregistered character"></i>
                    </li>
                {% endif %}

            {% endfor %}
        </ul>
    </div>
</div>

memberaudit/templates/memberaudit/partials/character_viewer/sidebar_character.html
{% load i18n %}
{% load evelinks %}

<img height="20" width="20" src="{{ character.character_id|character_portrait_url:32 }}"/>
<span
    {% if not character.memberaudit_character_pk %}class="text-muted"{% endif%}>{{ character.character_name }}

    {% if character.character_id == main_character_id %}
        &nbsp;<i class="fas fa-crown" title="{% translate 'Main character' %}"></i>
    {% endif %}

    {% if character.is_shared %}
        &nbsp;<i class="far fa-eye" title="{% translate 'Currently shared with recruiters' %}"></i>
    {% endif %}
</span>

memberaudit/templates/memberaudit/partials/character_viewer/tabs_navigation.html
{% load i18n %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation">
        <a href="#assets" aria-controls="assets" role="tab" data-toggle="tab">
            {% translate 'Assets' %}
            {% if is_assets_updating %}&nbsp;<i class="fas fa-exclamation-circle" title="{% translate 'Update in progress...' %}"></i>{% endif %}
        </a>
    </li>
    <li role="presentation"><a href="#attributes" aria-controls="attributes" role="tab" data-toggle="tab">{% translate 'Attributes' %}</a></li>
    <li role="presentation"><a href="#bio" aria-controls="bio" role="tab" data-toggle="tab">{% translate 'Bio' %}</a></li>
    <li role="presentation"><a href="#contacts" aria-controls="contacts" role="tab" data-toggle="tab">{% translate 'Contacts' %}</a></li>
    <li role="presentation"><a href="#contracts" aria-controls="contracts" role="tab" data-toggle="tab">{% translate 'Contracts' %}</a></li>
    <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">{% translate 'Corporations' %}</a></li>
    <li role="presentation"><a href="#implants" aria-controls="implants" role="tab" data-toggle="tab">{% translate 'Implants' %}</a></li>
    <li role="presentation"><a href="#clones" aria-controls="clones" role="tab" data-toggle="tab">{% translate 'Jump Clones' %}</a></li>
    <li role="presentation"><a href="#loyalty" aria-controls="loyalty" role="tab" data-toggle="tab">{% translate 'Loyalty' %}</a></li>
    <li role="presentation"><a href="#mail" aria-controls="mail" role="tab" data-toggle="tab">{% translate 'Mails' %}</a></li>
    <li role="presentation"><a href="#skillqueue" aria-controls="skillqueue" role="tab" data-toggle="tab">{% translate 'Skill Queue' %}</a></li>
    <li role="presentation"><a href="#skill_sets" aria-controls="skill_sets" role="tab" data-toggle="tab">{% translate 'Skill Sets' %}</a></li>
    <li role="presentation"><a href="#skills" aria-controls="skills" role="tab" data-toggle="tab">{% translate 'Skills' %}</a></li>
    <li class="dropdown active" role="presentation" role="tab" aria-controls="wallet">
        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">{% translate 'Wallet' %}&nbsp;<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
        <li class=""><a href="#wallet_journal" tabindex="-1" data-toggle="tab">{% translate 'Transactions' %}</a></li>
        <li class=""><a href="#wallet_transactions" tabindex="-1" data-toggle="tab">{% translate 'Market Transactions' %}</a></li>
        </ul>
    </li>
</ul>