memberaudit/urls.py
from django.urls import path

from .views import (
    admin,
    character_finder,
    character_viewer_1,
    character_viewer_2,
    characters,
    data_export,
    reports,
)

app_name = "memberaudit"

urlpatterns = [
    # characters
    path("", characters.index, name="index"),
    path("launcher", characters.launcher, name="launcher"),
    path("add_character", characters.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        characters.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        characters.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        characters.unshare_character,
        name="unshare_character",
    ),
    # character viewer
    path(
        "character_viewer/<int:character_pk>/",
        character_viewer_1.character_viewer,
        name="character_viewer",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        character_viewer_1.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        character_viewer_1.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        character_viewer_1.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        character_viewer_1.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        character_viewer_1.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        character_viewer_1.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        character_viewer_1.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        character_viewer_1.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        character_viewer_2.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        character_viewer_2.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        character_viewer_2.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail/<int:character_pk>/<int:mail_pk>/",
        character_viewer_2.character_mail,
        name="character_mail",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        character_viewer_2.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        character_viewer_2.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        character_viewer_2.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        character_viewer_2.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        character_viewer_2.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        character_viewer_2.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        character_viewer_1.character_attribute_data,
        name="character_attribute_data",
    ),
    # character finder
    path(
        "character_finder", character_finder.character_finder, name="character_finder"
    ),
    path(
        "character_finder_data",
        character_finder.CharacterFinderListJson.as_view(),
        name="character_finder_data",
    ),
    path(
        "character_finder_list_fdd_data",
        character_finder.character_finder_list_fdd_data,
        name="character_finder_list_fdd_data",
    ),
    # reports
    path("reports", reports.reports, name="reports"),
    path(
        "user_compliance_report_data",
        reports.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        reports.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        reports.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    # data export
    path("data-export/", data_export.data_export, name="data_export"),
    path(
        "data-export/run-update/<str:topic>",
        data_export.data_export_run_update,
        name="data_export_run_update",
    ),
    path(
        "data-export/download/<str:topic>",
        data_export.download_export_file,
        name="download_export_file",
    ),
    # admin
    path(
        "admin/create-skillset-from-fitting",
        admin.admin_create_skillset_from_fitting,
        name="admin_create_skillset_from_fitting",
    ),
]

memberaudit/views/character_finder.py
from dj_datatables_view.base_datatable_view import BaseDatatableView

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Case, Q, Value, When
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import format_html, format_html_join
from django.utils.safestring import mark_safe

from allianceauth.authentication.models import CharacterOwnership
from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag
from app_utils.views import (
    bootstrap_icon_plus_name_html,
    fontawesome_link_button_html,
    yesno_str,
)

from .. import __title__
from ..models import General
from ._common import add_common_context

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required("memberaudit.finder_access")
def character_finder(request) -> HttpResponse:
    context = {
        "page_title": "Character Finder",
    }
    return render(
        request,
        "memberaudit/character_finder.html",
        add_common_context(request, context),
    )


class CharacterFinderListJson(
    PermissionRequiredMixin, LoginRequiredMixin, BaseDatatableView
):
    model = CharacterOwnership
    permission_required = "memberaudit.finder_access"
    columns = [
        "character",
        "character_organization",
        "main_character",
        "main_organization",
        "state_name",
        "actions",
        "alliance_name",
        "corporation_name",
        "main_alliance_name",
        "main_corporation_name",
        "main_str",
        "unregistered_str",
        "character_id",
    ]

    # define column names that will be used in sorting
    # order is important and should be same as order of columns
    # displayed by datatables. For non sortable columns use empty
    # value like ''
    order_columns = [
        "character__character_name",
        "character__corporation_name",
        "user__profile__main_character__character_name",
        "user__profile__main_character__corporation_name",
        "user__profile__state__state_name",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]

    def get_initial_queryset(self):
        return self.initial_queryset(self.request)

    @classmethod
    def initial_queryset(cls, request):
        accessible_users = list(General.accessible_users(user=request.user))
        my_filter = Q(user__in=accessible_users)
        if request.user.has_perm("memberaudit.view_shared_characters"):
            my_filter |= Q(memberaudit_character__is_shared=True)
        character_ownerships = CharacterOwnership.objects.select_related(
            "character",
            "memberaudit_character",
            "user",
            "user__profile__main_character",
            "user__profile__state",
        ).filter(my_filter)
        return character_ownerships.annotate(
            unregistered=Case(
                When(memberaudit_character=None, then=Value("yes")),
                default=Value("no"),
            )
        )

    def filter_queryset(self, qs):
        """use parameters passed in GET request to filter queryset"""

        qs = self._apply_search_filter(qs, 4, "user__profile__state__name")
        qs = self._apply_search_filter(qs, 6, "character__alliance_name")
        qs = self._apply_search_filter(qs, 7, "character__corporation_name")
        qs = self._apply_search_filter(
            qs, 8, "user__profile__main_character__alliance_name"
        )
        qs = self._apply_search_filter(
            qs, 9, "user__profile__main_character__corporation_name"
        )
        qs = self._apply_search_filter(
            qs, 10, "user__profile__main_character__character_name"
        )
        qs = self._apply_search_filter(qs, 11, "unregistered")

        search = self.request.GET.get("search[value]", None)
        if search:
            qs = qs.filter(
                Q(character__character_name__istartswith=search)
                | Q(user__profile__main_character__character_name__istartswith=search)
            )
        return qs

    def _apply_search_filter(self, qs, column_num, field):
        my_filter = self.request.GET.get(f"columns[{column_num}][search][value]", None)
        if my_filter:
            if self.request.GET.get(f"columns[{column_num}][search][regex]", False):
                kwargs = {f"{field}__iregex": my_filter}
            else:
                kwargs = {f"{field}__istartswith": my_filter}
            return qs.filter(**kwargs)
        return qs

    def render_column(self, row, column):
        result = self._render_column_general(row, column)
        if result:
            return result
        result = self._render_column_auth_character(row, column)
        if result:
            return result
        result = self._render_column_main_character(row, column)
        if result:
            return result
        result = self._render_column_memberaudit_character(row, column)
        if result:
            return result
        return super().render_column(row, column)

    def _render_column_general(self, row, column):
        if column == "state_name":
            return row.user.profile.state.name
        if column == "unregistered_str":
            return row.unregistered
        return None

    def _render_column_auth_character(self, row, column):
        if column == "character_id":
            return row.character.character_id
        alliance_name = (
            row.character.alliance_name if row.character.alliance_name else ""
        )
        if column == "character_organization":
            return format_html(
                "{}<br><em>{}</em>",
                row.character.corporation_name,
                alliance_name,
            )
        if column == "alliance_name":
            return alliance_name
        if column == "corporation_name":
            return row.character.corporation_name
        return None

    def _render_column_main_character(self, row, column):
        try:
            main_character = row.user.profile.main_character
        except AttributeError:
            main_character = None
            is_main = False
        else:
            is_main = row.user.profile.main_character == row.character
            main_alliance_name = (
                main_character.alliance_name
                if main_character and main_character.alliance_name
                else ""
            )
        if column == "main_character":
            if main_character:
                return bootstrap_icon_plus_name_html(
                    main_character.portrait_url(),
                    main_character.character_name,
                    avatar=True,
                )
            return ""
        if column == "main_organization":
            if main_character:
                return format_html(
                    "{}<br><em>{}</em>",
                    main_character.corporation_name,
                    main_alliance_name,
                )
            return ""
        if column == "main_alliance_name":
            return main_alliance_name if main_character else ""
        if column == "main_corporation_name":
            return main_character.corporation_name if main_character else ""
        if column == "main_str":
            if main_character:
                return yesno_str(is_main)
            return ""
        return None

    def _render_column_memberaudit_character(self, row, column):
        try:
            character = row.memberaudit_character
        except ObjectDoesNotExist:
            character = None
            character_viewer_url = ""
        else:
            character_viewer_url = reverse(
                "memberaudit:character_viewer", args=[character.pk]
            )
        if column == "character":
            try:
                is_main = row.user.profile.main_character == row.character
            except AttributeError:
                is_main = False
            icons = []
            if is_main:
                icons.append(
                    mark_safe('<i class="fas fa-crown" title="Main character"></i>')
                )
            if character and character.is_shared:
                icons.append(
                    mark_safe('<i class="far fa-eye" title="Shared character"></i>')
                )
            if not character:
                icons.append(
                    mark_safe(
                        '<i class="fas fa-exclamation-triangle" title="Unregistered character"></i>'
                    )
                )
            character_text = format_html_join(
                mark_safe("&nbsp;"), "{}", ([html] for html in icons)
            )
            return bootstrap_icon_plus_name_html(
                row.character.portrait_url(),
                row.character.character_name,
                avatar=True,
                url=character_viewer_url,
                text=character_text,
            )
        if column == "actions":
            if character_viewer_url:
                actions_html = fontawesome_link_button_html(
                    url=character_viewer_url,
                    fa_code="fas fa-search",
                    button_type="primary",
                )
            else:
                actions_html = ""
            return actions_html
        return None


@login_required
@permission_required("memberaudit.finder_access")
def character_finder_list_fdd_data(request) -> JsonResponse:
    """Provide lists for drop down fields."""
    result = dict()
    qs = CharacterFinderListJson.initial_queryset(request)
    columns = request.GET.get("columns")
    if columns:
        for column in columns.split(","):

memberaudit/templates/memberaudit/base.html
{% extends 'allianceauth/base.html' %}

{% block page_title %}
    {{ page_title|striptags }} - {{ app_title }}
{% endblock %}

{% block content %}
    <br />
    <div class="aa-memberaudit">
        {% include 'memberaudit/partials/menu.html' %}
        <h2 class="text-left">{{ page_title }}</h2>
        {% block details %}{% endblock %}
    </div>
{% endblock %}

memberaudit/templates/memberaudit/character_finder.html
{% extends 'memberaudit/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}


{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate 'Characters' %}</h3>
        </div>

        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-width-fix" id="tab_characters">
                    <thead>
                        <tr>
                            <th>{% translate 'Character<br>Name' %}</th>
                            <th>{% translate 'Character<br>Organization' %}</th>
                            <th>{% translate 'Main<br>Name' %}</th>
                            <th>{% translate 'Main<br>Organization' %}</th>
                            <th>{% translate 'Main<br>State' %}</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
            <p class="text-muted">
                <i class="fas fa-crown"></i> Main character&nbsp;•&nbsp;
                <i class="far fa-eye"></i> Currently shared with recruiters
            </p>
        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}

    <!--load JS for filterDropDown plugin -->
    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/filterDropDown.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#tab_characters').DataTable({
                ajax: {
                    url: '{% url "memberaudit:character_finder_data" %}',
                    dataSrc: 'data',
                    cache: false
                },
                columns: [
                    { data: 'character' },
                    { data: 'character_organization' },
                    { data: 'main_character' },
                    { data: 'main_organization' },
                    { data: 'state_name' },
                    { data: 'actions' },
                    /* hidden columns */
                    { data: 'alliance_name' },
                    { data: 'corporation_name' },
                    { data: 'main_alliance_name' },
                    { data: 'main_corporation_name' },
                    { data: 'main_str' },
                    { data: 'unregistered_str' },
                ],

                columnDefs: [
                    { "orderable": false, "targets": [ 5 ] },
                    { "visible": false, "targets": [ 6, 7, 8, 9, 10, 11 ] },
                ],

                order: [ [ 0, "asc" ] ],

                searching: true,
                processing: true,
                serverSide: true,
                // stateSave: true,

                filterDropDown: {
                    columns: [
                        {
                            idx: 6,
                            title: "{% translate 'Char Alliance' %}"
                        },
                        {
                            idx: 7,
                            title: "{% translate 'Char Corporation' %}"
                        },
                        {
                            idx: 8,
                            title: "{% translate 'Main Alliance' %}"
                        },
                        {
                            idx: 9,
                            title: "{% translate 'Main Corporation' %}"
                        },
                        {
                            idx: 10,
                            title: "{% translate 'Main?' %}"
                        },
                        {
                            idx: 4,
                            title: "{% translate 'Main State' %}"
                        },
                        {
                            idx: 11,
                            title: "{% translate 'Unregistered?' %}"
                        },

                    ],
                    bootstrap: true,
                    ajax: '{% url "memberaudit:character_finder_list_fdd_data" %}'
                }
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/character_finder.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}

{% endblock %}

memberaudit/templates/memberaudit/launcher.html
{% extends 'memberaudit/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Characters' %}</h3>
        </div>
        <div class="panel-body">
            <!-- Characters -->
            <div class="character-cards">
                <ul class="cards_container">
                    <!-- Add New Character -->
                    <li class="cards_item">
                        <div class="card">
                            <div class="card-header">{% translate 'Register Character' %}</div>

                            <div class="card-body card__content">
                                <a href="{% url 'memberaudit:add_character' %}">
                                    <img src="{{ 1|character_portrait_url:256 }}" alt="Add character">
                                </a>
                            </div>

                            <div class="card-footer">
                                <a class="btn btn-primary btn-sm" href="{% url 'memberaudit:add_character' %}">{% translate 'Register' %}</a>
                            </div>
                        </div>
                    </li>

                    {% if has_registered_characters %}
                        <!-- Registered Characters -->
                        {% for auth_character in auth_characters|dictsort:"character_name" %}
                            <li class="cards_item">
                                <div class="card">
                                    <div class="card-header">
                                        {{ auth_character.character_name }}
                                        {% if auth_character.character_id == main_character_id %}
                                            &nbsp;<i class="fas fa-crown" title="Main character"></i>
                                        {% endif %}
                                        {% if auth_character.character.is_shared %}
                                            &nbsp;<i class="far fa-eye" title="Currently shared with recruiters"></i>
                                        {% endif %}
                                    </div>

                                    <div class="card-body card__content">
                                        <p>
                                            <a href="{% url 'memberaudit:character_viewer' auth_character.character.pk %}">
                                                <span class="aa-memberaudit-launcher-character-image">
                                                    <img src="{{ auth_character.character_id|character_portrait_url:256 }}" alt="{{ auth_character.character_name }}">

                                                    {% if auth_character.alliance_id %}
                                                        <span class="aa-memberaudit-alliance-logo">
                                                            <img class="" src="{{ auth_character.alliance_id|alliance_logo_url:64 }}" title="{{ auth_character.alliance_name }}">
                                                        </span>
                                                    {% endif %}

                                                    <span class="aa-memberaudit-corporation-logo">
                                                        <img class="" src="{{ auth_character.corporation_id|corporation_logo_url:64 }}" title="{{ auth_character.corporation_name }}">
                                                    </span>
                                                </span>
                                            </a>
                                        </p>

                                        <div class="text-center">
                                            {% include 'memberaudit/partials/solar_system.html' with character=auth_character.character only %}<br>
                                            {% if auth_character.character.wallet_balance %}
                                                {{ auth_character.character.wallet_balance.total|intword|default_if_none:"-" }} ISK<br>
                                            {% else %}
                                                <span class="text-muted">{% translate "(no data yet)" %}</span>
                                            {% endif %}

                                        </div>
                                    </div>

                                    <div class="card-footer">
                                        <a class="btn btn-success btn-sm" href="{% url 'memberaudit:character_viewer' auth_character.character.pk %}"
                                            role="button" title="{% translate 'View this character.' %}">
                                            <i class="fas fa-sign-in-alt"></i>
                                        </a>

                                        {% if perms.memberaudit.share_characters %}
                                            {% if auth_character.character.is_shared %}
                                                <a class="btn btn-primary btn-sm" href="{% url 'memberaudit:unshare_character' auth_character.character.pk %}"
                                                    role="button" title="{% translate 'Disable access to this character for recruiters.' %}">
                                                    <i class="far fa-eye-slash"></i>
                                                </a>
                                            {% else %}
                                                <a class="btn btn-warning btn-sm" href="{% url 'memberaudit:share_character' auth_character.character.pk %}"
                                                    role="button"
                                                    onclick="return confirm('Are you sure you want to SHARE this character?')"
                                                    title="{% translate 'Enable access to this character for recruiters.' %}">
                                                    <i class="far fa-eye"></i>
                                                </a>
                                            {% endif %}
                                        {% endif %}

                                        <a class="btn btn-danger btn-sm" href="{% url 'memberaudit:remove_character' auth_character.character.pk %}"
                                            role="button" title="{% translate 'Remove this character.' %}"
                                            onclick="return confirm('Are you sure you want to REMOVE this character?')">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            {% if unregistered_chars|length > 0 %}
                <p class="text-warning">
                    <strong>
                    <i class="fas fa-exclamation-triangle"></i>
                    {% translate 'Unregistered character(s):' %}&nbsp;&nbsp;</strong>
                    {{ unregistered_chars|join:", " }}
                </p>
            {% endif %}

            <p class="text-muted">
                <i class="fas fa-crown"></i> Main character&nbsp;•&nbsp;
                <i class="far fa-eye"></i> Currently shared with recruiters
            </p>
        </div>
    </div>

{% endblock details %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/launcher.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}